{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from {{cookiecutter.app_name}}.database import Column, Model, SurrogatePK, db, reference_col, relationship
from {{cookiecutter.app_name}}.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.Binary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/__init__.py
"""Main application package."""

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template

from {{cookiecutter.app_name}} import commands, public, user
from {{cookiecutter.app_name}}.extensions import bcrypt, cache, csrf_protect, db, debug_toolbar, login_manager, migrate, webpack


def create_app(config_object='{{cookiecutter.app_name}}.settings'):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__.split('.')[0])
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    register_shellcontext(app)
    register_commands(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    webpack.init_app(app)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        return {
            'db': db,
            'User': user.models.User}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.test)
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/401.html
{% raw %}
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© {{ cookiecutter.full_name }}</li>
  </ul>

    <ul class="footer-nav">
{% raw %}
      <li><a href="{{ url_for('public.about') }}">About</a></li>
{% endraw %}
      <li><a href="mailto:{{ cookiecutter.email }}">Contact</a></li>
    </ul>
  </small>
</footer>

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/layout.html
{% raw %}
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  {% endraw %}
    {{ cookiecutter.project_name }}
  {% raw %}
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>

<main role="main">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div><!-- end .alert -->
            {% endfor %}
          </div><!-- end col-md -->
        </div><!-- end row -->
{% endif %}
{% endwith %}

{% block content %}{% endblock %}
</main>


{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/nav.html
{% raw %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
    {% endraw %} {{cookiecutter.project_name}} {% raw %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/users/members.html
{% raw %}
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome {{ current_user.username }}</h1>
        <h3>This is the members-only page.</h3>
    </div>
{% endblock %}
{% endraw%}